version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_ABSOLUTE_URI: http://localhost:8082
    ports:
      - "8082:80"
    depends_on:
      - db

  secured_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secured_app:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - "8080:80"
    depends_on:
      - db

  unsecured_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./unsecured_app:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
